### ISSUE TITLE
Plugin incompatible with newer versions of phpstorm

### ISSUE THREAD

**Issue by clink-aaron** [vnea/intellij-plugin-quickly-change-editor-font-size-preference#2]
I'm getting a notice now in phpstorm:
```
Incompatible: requires IDE build 221.* or earlier
```
My current version of phpstorm is 2022.2.1.

**Comment by vnea** [comment]
Hello,

Yes, it is because a new version of PhpStorm has been released.
So I have to make a new release compatible with this new PhpStorm version.

I did not make a new release because **this feature is now built-in since version 2022.2**, you can follow [these instructions](https://www.jetbrains.com/help/rider/Zooming_in_the_Editor.html#use-ctrl-cmd-mouse-wheel-to-change-font-size-for-all-documents).

If it does not work for you, I can make a new release.

**Comment by clink-aaron** [comment]
Thank you for the clarification and the documentation. The built-in functionality works great.

**Comment by twidi** [comment]
Thanks for this wonderful plugin, I waited for a new release to update my pycharm and just found this issue. Maybe you should add a note about this on the plugin page!

Again, thanks a lot!

**Comment by vnea** [comment]
@twidi It's a good idea, I'll do it soon.

**Comment by vnea** [comment]
@twidi 

I released a new version `1.1.6` to add the disclaimer, thank's for your suggestion.

The plugin is also now compatible with IntelliJ 2022.2.x but this is the last update that I do.
